services:
  backend:
    build:
      context: ../backend
      dockerfile: ./docker/dockerfile.backend
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: ../backend
        target: /app
        consistency: cached
    environment:
      - NODE_ENV=development
    networks:
      - app-network

networks:
  app-network:
    driver: bridge